### ISSUE TITLE
Windows version in the future?

### ISSUE THREAD

**Issue by VoscRoty** [GenZmeY/KF2-Ranked-Patch#1]
Windows version in the future?

**Comment by GenZmeY** [comment]
I have no such plans, just posting what I have

but I won’t close this issue for now, if I suddenly get a windows version, I’ll write about it here

**Comment by GenZmeY** [comment]
Hey @VoscRoty !

Thanks to my good friend, a patch for kf2 server for windows is now available

You can apply it yourself by following the instructions in the [README](https://github.com/GenZmeY/KF2-Ranked-Patch/blob/master/README.md#windows) or take the patched file from the [releases](https://github.com/GenZmeY/KF2-Ranked-Patch/releases)

have fun! 🤗

**Comment by VoscRoty** [comment]
OMG, you helped everyone!
MY HERO!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GenZmeY/KF2-Ranked-Patch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月25日(星期四) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GenZmeY/KF2-Ranked-Patch] Windows version in the future? (Issue #1)





 
Hey @VoscRoty !
 
Thanks to my good friend, a patch for kf2 server for windows is now available
 
You can apply it yourself by following the instructions in the README or take the patched file from the releases
 
have fun! 🤗
